# Generated by Django 4.2.4 on 2023-09-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_wide',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
